version: '3.3'
services:
  backend:
    container_name: ${PROJECT_SLUG}_backend
    build:
      context: .
      dockerfile: ./docker/backend/${ENVIRONMENT}/Dockerfile
      args:
        - NODE_ENV=${ENVIRONMENT}
      target: runner
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./backend/config:/app/config
      - ./backend/src:/app/src
      - ./backend/package.json:/app/package.json
      - ./backend/yarn.lock:/app/yarn.lock
      - .env:/app/.env
      - ./backend/public/uploads:/app/public/uploads
      - ./logs/backend:/root/.npm/_logs
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - nginx
      - database
    depends_on:
      - postgres15
