version: '3.3'
services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    container_name: ${PROJECT_SLUG}_nginx
    volumes:
      - ./backend/public:/app/backend/public
      - ./frontend/public:/app/frontend/public
      - ./nginx/:/etc/nginx:ro
      - ./nginx/logs/:/var/log/nginx
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    depends_on:
      - frontend
      - backend
    networks:
      - nginx
    ports:
      - 80:80
      - 443:443

  frontend:
    extends:
      file: ./frontend/docker-compose.yml
      service: frontend

  backend:
    extends:
      file: ./backend/docker-compose.yml
      service: backend

  postgres15:
    image: postgres:15.2-alpine
    container_name: ${PROJECT_SLUG}_postgres
    platform: linux/amd64
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./db:/var/lib/postgresql/data/
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - database

networks:
  nginx:
    name: ${PROJECT_SLUG}_nginx
    driver: bridge
  app_bridge:
    name: ${PROJECT_SLUG}_app_bridge
    driver: bridge
  # DB NETWORK
  database:
    name: ${PROJECT_SLUG}_database
    driver: bridge
