version: '3.3'
services:
  frontend:
    container_name: ${PROJECT_SLUG}_frontend
    build:
      context: .
      dockerfile: ./docker/frontend/${ENVIRONMENT}/Dockerfile
      target: runner
      args:
        - NODE_ENV=${ENVIRONMENT}
      network: host
    restart: unless-stopped
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/tsconfig.json:/app/tsconfig.json
      - ./frontend/next.config.js:/app/next.config.js
      - ./frontend/next-env.d.ts:/app/next-env.d.ts
      - /app/node_modules
      - /app/.next
      - ./logs/frontend:/root/.npm/_logs
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    env_file:
      - .env
    networks:
      - app_bridge
    ports:
      - 80:3000
    depends_on:
      - backend

  backend:
    container_name: ${PROJECT_SLUG}_backend
    build:
      context: .
      dockerfile: ./docker/backend/${ENVIRONMENT}/Dockerfile
      args:
        - NODE_ENV=${ENVIRONMENT}
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./backend/config:/opt/backend/config
      - ./backend/src:/opt/backend/src
      - ./backend/package.json:/opt/package.json
      - ./backend/yarn.lock:/opt/yarn.lock
      - ./backend/public/uploads:/opt/backend/public/uploads
      - ./logs/backend:/root/.npm/_logs
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - app_bridge
      - database
    depends_on:
      - postgres15
    ports:
      - 1337:1337

  postgres15:
    image: postgres:15.2-alpine
    container_name: ${PROJECT_SLUG}_postgres
    platform: linux/amd64
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./db:/var/lib/postgresql/data/
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - database

networks:
  app_bridge:
    name: ${PROJECT_SLUG}_app_bridge
    driver: bridge
  database:
    name: ${PROJECT_SLUG}_database
    driver: bridge
