version: '3.3'
services:
  nginx_front:
    container_name: ${PROJECT_SLUG}_nginx_front
    extends:
      file: ./nginx/docker-compose.yml
      service: nginx
    volumes:
      - ./frontend/public:/app/frontend/public
      - ./nginx/frontend/:/etc/nginx:ro
    ports:
      - 80:80
      - 443:443

  frontend:
    extends:
      file: ./docker-compose-front.yml
      service: frontend
    networks:
      - app_bridge

  nginx_back:
    container_name: ${PROJECT_SLUG}_nginx_back
    extends:
      file: ./nginx/docker-compose.yml
      service: nginx
    volumes:
      - ./backend/public:/app/backend/public
      - ./nginx/backend/:/etc/nginx:ro
    ports:
      - 1337:8080

  backend:
    extends:
      file: ./docker-compose-back.yml
      service: backend
    depends_on:
      - postgres15
    networks:
      - app_bridge

  postgres15:
    image: postgres:15.2-alpine
    container_name: ${PROJECT_SLUG}_postgres
    platform: linux/amd64
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./db:/var/lib/postgresql/data/
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - database

networks:
  app_bridge:
    name: ${PROJECT_SLUG}_app_bridge
    driver: bridge
  nginx:
    name: ${PROJECT_SLUG}_nginx
    driver: bridge
  # DB NETWORK
  database:
    name: ${PROJECT_SLUG}_database
    driver: bridge
