version: '3.3'
services:
  frontend:
    container_name: ${PROJECT_SLUG}_frontend
    image: facej/s35-frontend:latest
    restart: unless-stopped
    volumes:
      - ./logs/frontend:/root/.npm/_logs
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    env_file:
      - .env
    networks:
      - app_bridge
    ports:
      - 3000:3000
    depends_on:
      - backend

  backend:
    container_name: ${PROJECT_SLUG}_backend
    image: facej/s35-backend:latest
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./logs/backend:/root/.npm/_logs
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - app_bridge
      - database
    depends_on:
      - postgres15
    ports:
      - 1337:1337

  postgres15:
    image: postgres:15.2-alpine
    container_name: ${PROJECT_SLUG}_postgres
    platform: linux/amd64
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./db:/var/lib/postgresql/data/
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - database

networks:
  app_bridge:
    name: ${PROJECT_SLUG}_app_bridge
    driver: bridge
  database:
    name: ${PROJECT_SLUG}_database
    driver: bridge
