name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Strapi backend the Docker image
      run: docker build . --file ../docker/backend/production/Dockerfile --tag my-image-name:$(date +%s)
#     - name: Build Next.js frontend the Docker image
#       run: docker build . --file ../docker/frontend/production/Dockerfile --tag my-image-name:$(date +%s)
